security:
    # https://symfony.com/doc/current/security/authenticator_manager.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        # App\Entity\User:
        #     algorithm: auto
        App\Entity\Producteur:
            algorithm: auto
        App\Entity\Consommateur:
            algorithm: auto





    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        # app_user_provider:
            # entity:
                # class: App\Entity\Consommateur
                # property: email
        app_producteur_provider:
            entity:
                class: App\Entity\Producteur
                property: email
        app_consommateur_provider:
            entity:
                class: App\Entity\Consommateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        consommateur_context:
            pattern: ^/consommateur
            lazy: true
            provider: app_consommateur_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            form_login:
                default_target_path : /
                check_path: /consommateur/login_check
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
        producteur_context:
            pattern: ^/producteur
            lazy: true
            provider: app_producteur_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            form_login:
                default_target_path : /
                check_path: /producteur/login_check
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            


            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
    role_hierarchy:
        ROLE_CONSOMMATEUR: ROLE_USER
        ROLE_PRODUCTEUR: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/producteur/login  , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/producteur  , roles: ROLE_PRODUCTEUR }
        - { path: ^/consommateur/login  , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/consommateur  , roles: ROLE_CONSOMMATEUR }
        - { path: ^/  , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/producteur/login_check  , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/consommateur/login_check  , roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
